version: "2"    
services:
  frontend:
    build: ./server/client         
    ports:
    - "3000:3000"            
    depends_on:
    - backend  
    networks:
    - movember-network       
  backend:
    build: ./server            
    ports:
    - "8000:8000"
    depends_on: 
    - mongo
    networks:
    - movember-network 
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - movember-network
networks:
  movember-network:
    driver: bridge
volumes:
  data-volume:
    driver: local
